<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:include filename="inertial_macros.xacro"/>

	<!-- Variables -->
	<xacro:property name="chassis_length" value="0.365"/>
    <xacro:property name="chassis_width" value="0.305"/>
	<xacro:property name="chassis_height" value="0.06"/>
	<xacro:property name="chassis_base_x_offset" value ="-0.081"/>
	<xacro:property name="chassis_base_y_offset" value ="0"/>
	<xacro:property name="chassis_base_z_offset" value ="0.028"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.04175"/>
    <xacro:property name="wheel_thickness" value="0.04977"/>
    <xacro:property name="wheel_mass" value="0.5"/>
    <xacro:property name="wheel_offset_x" value="0"/>
    <xacro:property name="wheel_offset_y" value="0.01578"/>
    <xacro:property name="wheel_offset_z" value="0"/>
    <xacro:property name="caster_wheel_mass" value="0.5"/>
	<xacro:property name="caster_wheel_offset_x" value="0.33175"/>
	<xacro:property name="caster_wheel_offset_y" value="0.11925"/>
    <xacro:property name="caster_wheel_offset_z" value="-${chassis_base_z_offset}"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

	
	<!-- BASE LINK -->

	
	<link name="base_link">

	</link>
	
	<joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
		<origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
	
	<link name="base_footprint">

	</link>

    <!-- Chasis -->


    <joint name="chasis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
		<origin xyz="${chassis_base_x_offset} ${chassis_base_y_offset} ${chassis_base_z_offset}" rpy="0 0 0"/>
    </joint>

	<link name="chassis">
		<visual>
			<origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
			<geometry>
				<box size ="${chassis_length} ${chassis_width} ${chassis_height}"/>
			</geometry>
			<material name="white"/>
		</visual>
		<collision>
			<origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
			<geometry>
				<box size ="${chassis_length} ${chassis_width} ${chassis_height}"/>
			</geometry>
		</collision>
		<xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
			<origin xyz="${chassis_length/2} 0 0" rpy="0 0 0"/>
		</xacro:inertial_box>
    	</link>


	<!-- Left wheel -->


	<joint name ="left_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_wheel"/>
		<origin xyz="0 ${chassis_width/2+wheel_thickness/2+wheel_offset_y} 0" rpy="-${pi/2} 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>

	<link name="left_wheel">
		<visual>
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
			</geometry>
			<material name ="blue"/>
		</visual>
		<collision>
			<geometry>
				<sphere radius="${wheel_radius}"/>
			</geometry>
		</collision>
		<xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_thickness}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_cylinder>

	</link>


	<!-- Right wheel -->


	<joint name ="right_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_wheel"/>
		<origin xyz="0 -${chassis_width/2+wheel_thickness/2+wheel_offset_y} 0" rpy="${pi/2} 0 0"/>
		<axis xyz="0 0 -1"/>
	</joint>

	<link name="right_wheel">
		<visual>
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
			</geometry>
			<material name ="blue"/>
		</visual>
		<collision>
			<geometry>
				<sphere radius="${wheel_radius}"/>
			</geometry>
		</collision>
		<xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_thickness}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_cylinder>


	</link>


	<!-- Caster wheel -->


	<joint name ="left_caster_wheel" type="fixed">
		<parent link ="chassis"/>
		<child link ="left_caster"/>
		<origin xyz="${caster_wheel_offset_x} ${caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
	</joint>

	<link name="left_caster">
		<visual>
			<geometry>
				<sphere radius="${wheel_radius}"/>
			</geometry>
			<material name ="black"/>
		</visual>
		<collision>
			<geometry>
				<sphere radius="${wheel_radius}"/>
			</geometry>
		</collision>
		<xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${wheel_radius}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_sphere>


	</link>

	<joint name ="right_caster_wheel" type="fixed">
		<parent link ="chassis"/>
		<child link ="right_caster"/>
		<origin xyz="${caster_wheel_offset_x} -${caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
	</joint>

	<link name="right_caster">
		<visual>
			<geometry>
				<sphere radius="${wheel_radius}"/>
			</geometry>
			<material name ="black"/>
		</visual>
		<collision>
			<geometry>
				<sphere radius="${wheel_radius}"/>
			</geometry>
		</collision>
		<xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${wheel_radius}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_sphere>


	</link>

	<gazebo reference="left_caster">
		<mu1 value="0.001"/>
		<mu2 value="0.001"/>
	</gazebo>

	<gazebo reference="right_caster">
		<mu1 value="0.001"/>
		<mu2 value="0.001"/>
	</gazebo>

</robot>
